# Generated by Django 4.0.4 on 2022-10-14 01:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acerto', models.CharField(max_length=200)),
                ('uuid', models.CharField(max_length=200)),
                ('exercicio', models.CharField(max_length=200)),
                ('performance', models.FloatField(default=0)),
                ('pontuacao_anterior', models.FloatField(default=0)),
                ('pontuacao_atual', models.FloatField(default=0)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'performance',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Parametro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tempoIdeal', models.IntegerField(default=5)),
                ('tempoSatisfatorio', models.IntegerField(default=15)),
                ('reforcoForte', models.FloatField(default=1.3)),
                ('reforcoMedio', models.FloatField(default=1.2)),
                ('reforcoFraco', models.FloatField(default=1.1)),
                ('pontuacaoMaxima', models.IntegerField(default=10)),
                ('pontuacaoMedia', models.IntegerField(default=5)),
                ('pontuacaoMinima', models.IntegerField(default=1)),
                ('pontuacaoFinal', models.IntegerField(default=100)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'parametro',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Contador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercicio', models.CharField(max_length=200)),
                ('tentativa', models.IntegerField(blank=True, null=True)),
                ('tempo', models.CharField(max_length=200)),
                ('acerto', models.CharField(max_length=200)),
                ('erro', models.CharField(max_length=200)),
                ('latencia', models.CharField(default='0', max_length=200)),
                ('coordenadaX', models.CharField(default='0', max_length=200)),
                ('coordenadaY', models.CharField(default='0', max_length=200)),
                ('latencia2', models.CharField(default='0', max_length=200)),
                ('coordenadaX2', models.CharField(default='0', max_length=200)),
                ('coordenadaY2', models.CharField(default='0', max_length=200)),
                ('latencia3', models.CharField(default='0', max_length=200)),
                ('coordenadaX3', models.CharField(default='0', max_length=200)),
                ('coordenadaY3', models.CharField(default='0', max_length=200)),
                ('latencia4', models.CharField(default='0', max_length=200)),
                ('coordenadaX4', models.CharField(default='0', max_length=200)),
                ('coordenadaY4', models.CharField(default='0', max_length=200)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'contador',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livapp.question')),
            ],
        ),
        migrations.CreateModel(
            name='Dados',
            fields=[
                ('ciclo', models.AutoField(primary_key=True, serialize=False)),
                ('avatar', models.CharField(choices=[('Menina2', 'Menina2'), ('Cachorro', 'Cachorro'), ('Menina', 'Menina'), ('Menino', 'Menino'), ('Coelho', 'Coelho'), ('Emoji', 'Emoji')], max_length=200)),
                ('tema_1', models.CharField(choices=[('Bola', 'Bola'), ('Carro', 'Carro'), ('Doce', 'Doce'), ('Livro', 'Livro')], max_length=200)),
                ('tema_2', models.CharField(choices=[('Bola', 'Bola'), ('Carro', 'Carro'), ('Doce', 'Doce'), ('Livro', 'Livro')], max_length=200)),
                ('tema_3', models.CharField(choices=[('Bola', 'Bola'), ('Carro', 'Carro'), ('Doce', 'Doce'), ('Livro', 'Livro')], max_length=200)),
                ('tema_4', models.CharField(choices=[('Bola', 'Bola'), ('Carro', 'Carro'), ('Doce', 'Doce'), ('Livro', 'Livro')], max_length=200)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dados',
                'managed': True,
                'unique_together': {('aluno', 'ciclo')},
            },
        ),
    ]
