# Generated by Django 4.0.4 on 2022-10-14 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='tempo',
            field=models.FloatField(default=0),
        ),
    ]
