# Generated by Django 4.0.4 on 2022-10-14 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livapp', '0002_performance_tempo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='acerto',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='performance',
            name='exercicio',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='performance',
            name='performance',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='performance',
            name='pontuacao_anterior',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='performance',
            name='pontuacao_atual',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='performance',
            name='tempo',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='performance',
            name='uuid',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
