# Generated by Django 4.0.4 on 2022-10-14 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livapp', '0003_alter_performance_acerto_alter_performance_exercicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='distancia',
            field=models.FloatField(default=0, null=True),
        ),
    ]
