# Generated by Django 4.0.4 on 2023-10-20 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livapp', '0004_performance_distancia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200, null=True)),
                ('password', models.CharField(max_length=200, null=True)),
                ('key', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'usuarios',
                'managed': True,
            },
        ),
    ]
